### ISSUE TITLE
Foursquare dataset and preprocessing script

### ISSUE THREAD

**Issue by falcaopetri** [trajminer/data#2]
I created PR #1 to add a script that gets the original Foursquare datasets (from [here](http://www-public.it-sudparis.eu/~zhang_da/pub/dataset_tsmc2014.zip)) and preprocess them to generate the datasets in this repo (added in commit b19b3f0).

While testing, I noticed that although the script output was exactly equal to the data in this repo, the data itself was not exactly equal to the original.

Then, I verified that numerical rounding issues are introduced during the reading/writing process. I suppose it doesn't make any difference, but it may be good to be aware of this.

The following is a side-by-side diff of a subset of the values:

| Original NYC values  | Preprocessed data values |
|---------------------------------------|----------------------------------------|
| **40.60679958140643** -74.04416981025437  | **40.606799581406435** -74.04416981025437 |
| **40.716161684843215** -73.88307005845945 | **40.71616168484322** -73.88307005845945  |
| 40.7451638 -73.982518775              | 40.7451638 -73.982518775               |
| 40.74010382743943 -73.98965835571289  | 40.74010382743943 -73.98965835571289   |
| 40.69042711809854 **-73.95468677509598**  | 40.69042711809854 **-73.954686775096**    |
| **40.751591431346306** -73.9741214009634  | **40.75159143134631** -73.9741214009634   |
| 40.77942173066975 -73.95534113280371  | 40.77942173066975 -73.95534113280371   |
| 40.61915106755737 -74.03588760058483  | 40.61915106755737 -74.03588760058483   |
| 40.61900594093755 -73.99037472596906  | 40.61900594093755 -73.99037472596906   |

**Comment by lucaspetry** [comment]
I believe the differences reported here are negligible (we have 13 decimal places!). I would even say that the numbers after the eighth or nineth decimal place are just random, as GPS devices hardly ever achieve such level of accuracy ([see this](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude)). Anyways, thank you for pointing that out.
